/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router. Do not edit it directly.

import { Route as rootRoute } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as LabBlocksRouteImport } from "./routes/lab/blocks";
import { Route as LabKitchenRouteImport } from "./routes/lab/kitchen";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const LabBlocksRoute = LabBlocksRouteImport.update({
  id: "/lab/blocks",
  path: "/lab/blocks",
  getParentRoute: () => rootRoute,
} as any);

const LabKitchenRoute = LabKitchenRouteImport.update({
  id: "/lab/kitchen",
  path: "/lab/kitchen",
  getParentRoute: () => rootRoute,
} as any);

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/lab/blocks": {
      id: "/lab/blocks";
      path: "/lab/blocks";
      fullPath: "/lab/blocks";
      preLoaderRoute: typeof LabBlocksRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/lab/kitchen": {
      id: "/lab/kitchen";
      path: "/lab/kitchen";
      fullPath: "/lab/kitchen";
      preLoaderRoute: typeof LabKitchenRouteImport;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute
  ._addFileChildren({
    IndexRoute,
    LabBlocksRoute,
    LabKitchenRoute,
  })
  ._addFileTypes<FileRoutesByPath>();
