/* eslint-disable */
// @ts-nocheck
// This file is generated by TanStack Router. Do not edit it directly.

import { Route as rootRoute } from "./routes/__root";
import { Route as AgentSetupRouteImport } from "./routes/agent-setup";
import { Route as AgentSetupKindRouteImport } from "./routes/agent-setup.$kind";
import { Route as ChatsRouteImport } from "./routes/chats";
import { Route as ChatsIdRouteImport } from "./routes/chats.$id";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as IntentsRouteImport } from "./routes/intents";
import { Route as SkillsRouteImport } from "./routes/skills";
import { Route as SkillsIdRouteImport } from "./routes/skills.$id";
import { Route as ToolsScopeNameRouteImport } from "./routes/tools/$scope/$name";
import { Route as ToolsNewRouteImport } from "./routes/tools/new";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRoute,
} as any);

const AgentSetupRoute = AgentSetupRouteImport.update({
  id: "/agent-setup",
  path: "/agent-setup",
  getParentRoute: () => rootRoute,
} as any);

const AgentSetupKindRoute = AgentSetupKindRouteImport.update({
  id: "/agent-setup/$kind",
  path: "/agent-setup/$kind",
  getParentRoute: () => rootRoute,
} as any);

const ChatsRoute = ChatsRouteImport.update({
  id: "/chats",
  path: "/chats",
  getParentRoute: () => rootRoute,
} as any);

const ChatsIdRoute = ChatsIdRouteImport.update({
  id: "/chats/$id",
  path: "/chats/$id",
  getParentRoute: () => rootRoute,
} as any);

const IntentsRoute = IntentsRouteImport.update({
  id: "/intents",
  path: "/intents",
  getParentRoute: () => rootRoute,
} as any);

const SkillsRoute = SkillsRouteImport.update({
  id: "/skills",
  path: "/skills",
  getParentRoute: () => rootRoute,
} as any);

const SkillsIdRoute = SkillsIdRouteImport.update({
  id: "/skills/$id",
  path: "/skills/$id",
  getParentRoute: () => rootRoute,
} as any);

const ToolsNewRoute = ToolsNewRouteImport.update({
  id: "/tools/new",
  path: "/tools/new",
  getParentRoute: () => rootRoute,
} as any);

const ToolsScopeNameRoute = ToolsScopeNameRouteImport.update({
  id: "/tools/$scope/$name",
  path: "/tools/$scope/$name",
  getParentRoute: () => rootRoute,
} as any);

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/agent-setup": {
      id: "/agent-setup";
      path: "/agent-setup";
      fullPath: "/agent-setup";
      preLoaderRoute: typeof AgentSetupRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/agent-setup/$kind": {
      id: "/agent-setup/$kind";
      path: "/agent-setup/$kind";
      fullPath: "/agent-setup/$kind";
      preLoaderRoute: typeof AgentSetupKindRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/chats": {
      id: "/chats";
      path: "/chats";
      fullPath: "/chats";
      preLoaderRoute: typeof ChatsRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/chats/$id": {
      id: "/chats/$id";
      path: "/chats/$id";
      fullPath: "/chats/$id";
      preLoaderRoute: typeof ChatsIdRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/intents": {
      id: "/intents";
      path: "/intents";
      fullPath: "/intents";
      preLoaderRoute: typeof IntentsRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/skills": {
      id: "/skills";
      path: "/skills";
      fullPath: "/skills";
      preLoaderRoute: typeof SkillsRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/skills/$id": {
      id: "/skills/$id";
      path: "/skills/$id";
      fullPath: "/skills/$id";
      preLoaderRoute: typeof SkillsIdRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/tools/new": {
      id: "/tools/new";
      path: "/tools/new";
      fullPath: "/tools/new";
      preLoaderRoute: typeof ToolsNewRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/tools/$scope/$name": {
      id: "/tools/$scope/$name";
      path: "/tools/$scope/$name";
      fullPath: "/tools/$scope/$name";
      preLoaderRoute: typeof ToolsScopeNameRouteImport;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute
  ._addFileChildren({
    AgentSetupRoute,
    AgentSetupKindRoute,
    ChatsRoute,
    ChatsIdRoute,
    IndexRoute,
    IntentsRoute,
    SkillsRoute,
    SkillsIdRoute,
    ToolsNewRoute,
    ToolsScopeNameRoute,
  })
  ._addFileTypes<FileRoutesByPath>();
